# Configuración del Puerto
server.port=8080

# Configuración de Thymeleaf (Sin caché para desarrollo)
spring.thymeleaf.cache=false

# Configuración de Base de Datos H2
spring.datasource.url=jdbc:h2:mem:alcancia_ddd
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar consola de H2 para inspeccionar la base en: http://localhost:8080/h2-console
spring.h2.console.enabled=true